/*====================================================*
*				UNIVERSIDAD MARIANO GALVEZ		      *
*			FACULTAD DE INGENIERIA EN SISTEMAS        *
*												      *
*	SECCION    : 'A'                                  *
*	CURSO      : ANALISIS DE SISTEMAS I				  *
*	PROYECTO   : GESTOR DE LA BIBLIOTECA UNIBIBLIO	  *
*	DESCRIPCION: CREACION DE LA BASE DE DATOS		  *
*	FECHA	   : 14/04/2023							  *
*=====================================================*/

CREATE DATABASE BD_UNIBIBLIO
GO
USE BD_UNIBIBLIO
GO
CREATE SCHEMA UMG


--> CREACION DE TABLAS

CREATE TABLE [BD_UNIBIBLIO].[UMG].TIPO_PRESTAMO (
  ID_TIPO_PRESTAMO INT PRIMARY KEY,
  DESCRIPCION VARCHAR(100),
  ESTATUS VARCHAR(50)
)

CREATE TABLE [BD_UNIBIBLIO].[UMG].USUARIO (
  ID_USUARIO INT PRIMARY KEY,
  NOMBRE VARCHAR(100),
  APELLIDO VARCHAR(100),
  DPI INT,
  TELEFONO INT,
  CORREO VARCHAR(100),
  DOMICILIO VARCHAR(100),
  LIBROS_PRESTADOS INT,
  DEUDA	DECIMAL(18,2),
  ID_ESTATUS INT,
  ID_GRUPO INT
)

Create Table [BD_UNIBIBLIO].[UMG].GRUPO_LIB 
(
	ID_GRUPO INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(20),
	ESTATUS VARCHAR(20) 
)


Create Table [BD_UNIBIBLIO].[UMG].ESTATUS
(
	ID_ESTATUS INT NOT NULL PRIMARY KEY,
	DESCRIPCION VARCHAR(20)
)


CREATE TABLE [BD_UNIBIBLIO].[UMG].GRUPO
(
	ID_GRUPO			INT NOT NULL,
	DESCRIPCION			VARCHAR(100) NOT NULL,
	ESTATUS				VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID_GRUPO)
)

Create Table [BD_UNIBIBLIO].[UMG].LIBROS
(
	ID_LIBRO int not null primary key,
	TITULO VARCHAR (100),
	TEMATICA VARCHAR (100),
	AUTOR VARCHAR (50),
	CANTIDAD INT,
	ID_GRUPO INT,
	FECHA_INGRESO DATE
)

ALTER TABLE [BD_UNIBIBLIO].[UMG].LIBROS ADD FECHA_INGRESO DATE

ALTER TABLE [BD_UNIBIBLIO].[UMG].LIBROS ADD FOREIGN KEY (ID_GRUPO) REFERENCES [BD_UNIBIBLIO].[UMG].GRUPO_LIB (ID_GRUPO);

Create table [BD_UNIBIBLIO].[UMG].PRESTAMO
(
	ID_PRESTAMO int not null primary key,
	ID_USUARIO int not null,
	ID_TIPO_PRESTAMO int,
	FECHA_SOL date,
	FECHA_DEV date
)

ALTER TABLE [BD_UNIBIBLIO].[UMG].PRESTAMO ADD FOREIGN KEY (ID_TIPO_PRESTAMO) REFERENCES [BD_UNIBIBLIO].[UMG].TIPO_PRESTAMO (ID_TIPO_PRESTAMO);
ALTER TABLE [BD_UNIBIBLIO].[UMG].PRESTAMO ADD FOREIGN KEY (ID_USUARIO) REFERENCES [BD_UNIBIBLIO].[UMG].USUARIO (ID_USUARIO);

Create table [BD_UNIBIBLIO].[UMG].DETALLE_PRESTAMO
(
	ID_DETALLE_PRESTAMO int not null primary key,
	ID_PRESTAMO int,
	ID_LIBRO INT,
	CANTIDAD INT
)

ALTER TABLE [BD_UNIBIBLIO].[UMG].DETALLE_PRESTAMO ADD FOREIGN KEY (ID_PRESTAMO) REFERENCES [BD_UNIBIBLIO].[UMG].PRESTAMO (ID_PRESTAMO);
ALTER TABLE [BD_UNIBIBLIO].[UMG].DETALLE_PRESTAMO ADD FOREIGN KEY (ID_LIBRO) REFERENCES [BD_UNIBIBLIO].[UMG].LIBROS (ID_LIBRO);


INSERT INTO [BD_UNIBIBLIO].[UMG].GRUPO_LIB(ID_GRUPO,DESCRIPCION,ESTATUS) VALUES (1,'DRAMA JUVENIL','VIGENTE')

INSERT INTO [BD_UNIBIBLIO].[UMG].LIBROS(ID_LIBRO,TITULO,TEMATICA,AUTOR,CANTIDAD,ID_GRUPO) VALUES(1,'LAS VENTAJAS DE SER INVISIBLE','DRAMA','STEPHEN CHBOSKY',4,1)